export const TRUSTED_PAGE_PATHS = [
	{ path: "contact", weight: 50 },
	{ path: "contact-us", weight: 50 },
	{ path: "team", weight: 45 },
	{ path: "our-team", weight: 45 },
	{ path: "staff", weight: 45 },
	{ path: "leadership", weight: 45 },
	{ path: "people", weight: 45 },
	{ path: "privacy", weight: 45 },
	{ path: "about", weight: 40 },
	{ path: "about-us", weight: 40 },
	{ path: "legal", weight: 40 },
	{ path: "terms", weight: 40 },
	{ path: "careers", weight: 35 },
	{ path: "jobs", weight: 35 },
	{ path: "help", weight: 35 },
	{ path: "support", weight: 35 },
	{ path: "press", weight: 30 },
	{ path: "media", weight: 30 },
	{ path: "newsroom", weight: 30 },
	{ path: "blog", weight: 15 },
	{ path: "news", weight: 15 },
] as const;
